# Generated by Django 2.0.4 on 2018-04-29 23:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutableCipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('isReady', models.BooleanField(default=False)),
                ('binary', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JSCipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('isReady', models.BooleanField(default=False)),
                ('encryptFun', models.TextField(blank=True)),
                ('decryptFun', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partipicant',
            fields=[
                ('nick', models.CharField(max_length=128)),
                ('password_hash', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PythonCipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('isReady', models.BooleanField(default=False)),
                ('encryptFun', models.TextField(blank=True)),
                ('decryptFun', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_app.Partipicant')),
            ],
        ),
        migrations.AddField(
            model_name='jscipher',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_app.Partipicant'),
        ),
        migrations.AddField(
            model_name='executablecipher',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_app.Partipicant'),
        ),
    ]
